# Master passwords are generated by Terraform and stored only in Secrets Manager,
# encrypted with the platform CMK. They are never written to tfvars or committed.
# In production these secrets would have rotation enabled via a rotation Lambda.

resource "random_password" "oracle" {
  length  = 24
  special = true
  # Oracle disallows a handful of characters in passwords.
  override_special = "_-#"
}

resource "random_password" "aurora" {
  length           = 24
  special          = true
  override_special = "_-#"
}

resource "aws_secretsmanager_secret" "oracle" {
  name        = "${var.name_prefix}/oracle/master"
  description = "Oracle master credentials"
  kms_key_id  = var.kms_key_arn
}

resource "aws_secretsmanager_secret_version" "oracle" {
  secret_id = aws_secretsmanager_secret.oracle.id
  secret_string = jsonencode({
    username = var.oracle_username
    password = random_password.oracle.result
    engine   = "oracle"
    port     = 1521
  })
}

resource "aws_secretsmanager_secret" "aurora" {
  name        = "${var.name_prefix}/aurora/master"
  description = "Aurora MySQL master credentials"
  kms_key_id  = var.kms_key_arn
}

resource "aws_secretsmanager_secret_version" "aurora" {
  secret_id = aws_secretsmanager_secret.aurora.id
  secret_string = jsonencode({
    username = var.aurora_username
    password = random_password.aurora.result
    engine   = "mysql"
    port     = 3306
  })
}
