# Master passwords are generated by Terraform and stored only in Secrets Manager,
# encrypted with the platform CMK. They are never written to tfvars or committed.
# In production these secrets would have rotation enabled via a rotation Lambda.

resource "random_password" "oracle" {
  length  = 24
  special = true
  # Oracle disallows a handful of characters in passwords.
  override_special = "_-#"
}

resource "random_password" "aurora" {
  length           = 24
  special          = true
  override_special = "_-#"
}

resource "aws_secretsmanager_secret" "oracle" {
  name        = "${var.name_prefix}/oracle/master"
  description = "Oracle master credentials"
  kms_key_id  = var.kms_key_arn
}

resource "aws_secretsmanager_secret_version" "oracle" {
  secret_id = aws_secretsmanager_secret.oracle.id
  secret_string = jsonencode({
    username = var.oracle_username
    password = random_password.oracle.result
    engine   = "oracle"
    port     = 1521
  })
}

resource "aws_secretsmanager_secret" "aurora" {
  name        = "${var.name_prefix}/aurora/master"
  description = "Aurora MySQL master credentials"
  kms_key_id  = var.kms_key_arn
}

resource "aws_secretsmanager_secret_version" "aurora" {
  secret_id = aws_secretsmanager_secret.aurora.id
  secret_string = jsonencode({
    username = var.aurora_username
    password = random_password.aurora.result
    engine   = "mysql"
    port     = 3306
  })
}

# --- Credential rotation (production) ---
# checkov CKV2_AWS_57 flags these secrets as lacking automatic rotation. In
# production, rotation is handled by the AWS-managed RDS rotation Lambda, wired as
# below. It is kept commented in this showcase to avoid provisioning a Lambda (and
# its VPC plumbing) solely to satisfy a static check — the intent is explicit and
# CKV2_AWS_57 is baselined in .checkov.yml with this justification.
#
# resource "aws_secretsmanager_secret_rotation" "oracle" {
#   secret_id           = aws_secretsmanager_secret.oracle.id
#   rotation_lambda_arn = var.rotation_lambda_arn
#   rotation_rules {
#     automatically_after_days = 30
#   }
# }
#
# resource "aws_secretsmanager_secret_rotation" "aurora" {
#   secret_id           = aws_secretsmanager_secret.aurora.id
#   rotation_lambda_arn = var.rotation_lambda_arn
#   rotation_rules {
#     automatically_after_days = 30
#   }
# }
